import { createHash } from "node:crypto";
import { getMcpGroup } from "./mcp.js";
import { KNOWN_TOOLS } from "./tools.js";
import type { SkillDefinition } from "./types.js";

/** Adapter targets. Directory names live here only; changing `.agent` to `.agents` is a one-line edit. */
export const SKILL_TARGETS = {
  claude: ".claude/skills",
  agent: ".agent/skills",
} as const;
export type SkillTarget = keyof typeof SKILL_TARGETS;

export const GENERATED_MARKER = "generated by skills:sync";
const MARKER_RE = /^<!-- generated by skills:sync from src\/skills\/catalog\.ts\. Do not edit; run `npm run skills:sync`\. hash:([0-9a-f]{12}) -->$/m;

export function shortHash(text: string): string {
  return createHash("sha256").update(text).digest("hex").slice(0, 12);
}

/** Which targets get a generated SKILL.md for this skill. Manual skills and undocumented planned ones get none. */
export function targetsFor(skill: SkillDefinition): SkillTarget[] {
  if (skill.manual) return [];
  if (skill.status !== "implemented" && !skill.documented) return [];
  return skill.environmentSupport === "both" ? ["claude", "agent"] : [skill.environmentSupport];
}

const list = (items: readonly string[], empty: string): string => (items.length === 0 ? empty : items.map((i) => `- ${i}`).join("\n"));

const ENV_NOTE: Record<SkillTarget, string> = {
  claude: "Claude Code reads this file as advisory instructions. It is not enforced here; AgentLab enforces permissions only on its own runtime agents.",
  agent: "An agent-environment assistant (for example Antigravity) reads this file as advisory instructions. It is not enforced here; AgentLab enforces permissions only on its own runtime agents.",
};

/** Body without the generated marker; the hash covers exactly this text. */
function renderBody(skill: SkillDefinition, target: SkillTarget): string {
  const tools = skill.tools.map((t) => `\`${t}\` (needs ${KNOWN_TOOLS[t] ?? "?"})`);
  const mcp = skill.mcpGroups.map((g) => `\`${g}\`: ${getMcpGroup(g)?.status ?? "unknown"}`);
  const parts = [
    `# ${skill.name}`,
    skill.instructions.trim(),
    `## Permissions\n${list(skill.permissions.map((p) => `\`${p}\``), "None. This skill grants no permissions.")}`,
    `## Tools and device actions\n${list([...tools, ...skill.actions.map((a) => `action \`${a}\``)], "None.")}`,
    `## MCP\n${list(mcp, "None.")}`,
    `## Dependencies\n${list(skill.dependencies.map((d) => `\`${d}\``), "None.")}`,
    `## Status\nstatus: ${skill.status} | security level: ${skill.securityLevel} | version: ${skill.version} | category: ${skill.category}`,
    `## Environment: ${target}\n${ENV_NOTE[target]}${skill.perEnvironment?.[target] ? `\n\n${skill.perEnvironment[target]!.trim()}` : ""}`,
  ];
  return `${parts.join("\n\n")}\n`;
}

function frontmatter(skill: SkillDefinition): string {
  // Only name + description: the common subset of Claude Code and agent-environment skill formats.
  return `---\nname: ${skill.id}\ndescription: ${JSON.stringify(skill.description.replace(/\s+/g, " ").trim())}\n---\n`;
}

export function renderSkill(skill: SkillDefinition, target: SkillTarget): string {
  const body = renderBody(skill, target);
  const marker = `<!-- ${GENERATED_MARKER} from src/skills/catalog.ts. Do not edit; run \`npm run skills:sync\`. hash:${shortHash(body)} -->`;
  return `${frontmatter(skill)}${marker}\n\n${body}`;
}

export interface ParsedSkillFile {
  readonly name?: string;
  readonly description?: string;
  readonly body: string;
}

/** Minimal parser for the two-field frontmatter used by these files (no YAML dependency). */
export function parseSkillFile(text: string): ParsedSkillFile {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(text);
  if (!m) return { body: text };
  const out: { name?: string; description?: string } = {};
  for (const line of m[1]!.split(/\r?\n/)) {
    const kv = /^(name|description):\s*(.*)$/.exec(line);
    if (!kv) continue;
    let value = kv[2]!.trim();
    if (value.startsWith('"')) {
      try {
        value = JSON.parse(value) as string;
      } catch {
        /* keep raw */
      }
    }
    out[kv[1] as "name" | "description"] = value;
  }
  return { ...out, body: m[2]! };
}

/** If the file is a generated one, returns whether its recorded hash still matches its body. */
export function checkGeneratedHash(text: string): "not-generated" | "ok" | "tampered" {
  const parsed = parseSkillFile(text);
  const marker = MARKER_RE.exec(parsed.body);
  if (!marker) return text.includes(GENERATED_MARKER) ? "tampered" : "not-generated";
  const body = parsed.body.replace(/^<!--[^\n]*-->\n\n/, "");
  return shortHash(body) === marker[1] ? "ok" : "tampered";
}
